import { PROVIDER_REGISTRY, type ProviderMetadata } from "@better-captcha/core";
import { generateAggregateIndexFile } from "@better-captcha/core/utils/build-plugin-utils";
import type { UnpluginFactory } from "unplugin";
import { createUnplugin } from "unplugin";

function generateComponent(metadata: ProviderMetadata): string {
	const { name, componentName, providerClassName, identifierProp = "sitekey" } = metadata;
	return `import { createCaptchaComponent } from "../../create-captcha-component.js";
import { ${providerClassName} } from "@better-captcha/core/providers/${name}";
export const ${componentName} = createCaptchaComponent(${providerClassName}, "${identifierProp}");
`;
}

function generateComponentDts(metadata: ProviderMetadata): string {
	const {
		name,
		componentName,
		handleType,
		renderParamsType,
		renderParamsOmit,
		extraTypes,
		solvePayloadType,
		identifierProp = "sitekey",
	} = metadata;

	const extraTypeImports = extraTypes.length > 0 ? `,\n\t${extraTypes.join(",\n\t")}` : "";
	const extraTypeExports = extraTypes.length > 0 ? `, ${extraTypes.join(", ")}` : "";
	const solveType = solvePayloadType ?? "string";

	const propsTypeModifier = identifierProp === "endpoint"
		? `Omit<CaptchaProps<Omit<${renderParamsType}, ${renderParamsOmit}>, ${solveType}>, "sitekey"> & { endpoint: string }`
		: `Omit<CaptchaProps<Omit<${renderParamsType}, ${renderParamsOmit}>, ${solveType}>, "endpoint"> & { sitekey: string }`;

	return `// Auto-generated from @better-captcha/core
// Do not edit this file directly
import type { DefineComponent } from "vue";
import type { CaptchaProps, CaptchaEmits } from "../../index.js";
import type {
\t${handleType},
\t${renderParamsType}${extraTypeImports}
} from "@better-captcha/core/providers/${name}";

export declare const ${componentName}: DefineComponent<${propsTypeModifier}, CaptchaEmits<${handleType}, ${solveType}>>;
export type { ${handleType}, ${renderParamsType}${extraTypeExports} };
`;
}

export const unpluginFactory: UnpluginFactory<undefined> = () => {
	const VIRTUAL_ID = "virtual:better-captcha-providers";
	const RESOLVED_VIRTUAL_ID = "\0better-captcha-providers";

	return {
		name: "better-captcha-generate-components",
		rollup: {
			resolveId(id) {
				return id === VIRTUAL_ID ? RESOLVED_VIRTUAL_ID : null;
			},
			load(id) {
				if (id === RESOLVED_VIRTUAL_ID) {
					return 'export * from "./provider/index.js";';
				}
				return null;
			},
			generateBundle() {
				for (const provider of PROVIDER_REGISTRY) {
					const js = generateComponent(provider);
					const dts = generateComponentDts(provider);

					this.emitFile({
						type: "asset",
						fileName: `provider/${provider.name}/index.js`,
						source: js,
					});

					this.emitFile({
						type: "asset",
						fileName: `provider/${provider.name}/index.d.ts`,
						source: dts,
					});
				}

				const aggregateFiles = generateAggregateIndexFile(PROVIDER_REGISTRY, ".js");

				this.emitFile({
					type: "asset",
					fileName: "provider/index.js",
					source: aggregateFiles.js,
				});

				this.emitFile({
					type: "asset",
					fileName: "provider/index.d.ts",
					source: aggregateFiles.dts,
				});
			},
		},
	};
};

export const unplugin = createUnplugin(unpluginFactory);
export default unplugin;
export const rollupPlugin = unplugin.rollup;
