import { PROVIDER_REGISTRY, type ProviderMetadata } from "@better-captcha/core";
import { generateProviderAssets } from "@better-captcha/core/utils/build-plugin-utils";
import type { UnpluginFactory } from "unplugin";
import { createUnplugin } from "unplugin";

function generateComponent(metadata: ProviderMetadata): string {
	let elementName = metadata.name.endsWith("-captcha") ? metadata.name : `${metadata.name}-captcha`;

	if (elementName === "private-captcha") {
		elementName = "private-captcha-widget";
	}

	return `import { createCaptchaComponent } from "../../base-captcha.js";
import { ${metadata.providerClassName} } from "@better-captcha/core/providers/${metadata.name}";
export const ${metadata.componentName} = createCaptchaComponent(${metadata.providerClassName}, "${elementName}");
`;
}

function generateComponentDts(metadata: ProviderMetadata): string {
	const { name, componentName, handleType, renderParamsType, extraTypes } = metadata;

	const extraTypeImports = extraTypes.length > 0 ? `,\n\t${extraTypes.join(",\n\t")}` : "";
	const extraTypeExports = extraTypes.length > 0 ? `, ${extraTypes.join(", ")}` : "";

	return `// Auto-generated from @better-captcha/core
// Do not edit this file directly
import type {
	${handleType},
	${renderParamsType}${extraTypeImports}
} from "@better-captcha/core/providers/${name}";

export declare const ${componentName}: CustomElementConstructor;
export type { ${handleType}, ${renderParamsType}${extraTypeExports} };
`;
}

export const unpluginFactory: UnpluginFactory<undefined> = () => {
	return {
		name: "better-captcha-generate-components",
		rollup: {
			generateBundle() {
				for (const asset of generateProviderAssets(PROVIDER_REGISTRY, (provider) => ({
					js: generateComponent(provider),
					dts: generateComponentDts(provider),
				}))) {
					this.emitFile({ type: "asset", ...asset });
				}
			},
		},
	};
};

export const unplugin = createUnplugin(unpluginFactory);
export default unplugin;
export const rollupPlugin = unplugin.rollup;
